apiVersion: v1
kind: Service                      # Type of the kubernetes resource
metadata:      
  name: willow-api                 # Name of the Kubernetes resource
  labels:                          # Labels that will be applied to the resource
    run: willow-api
spec:
  type: NodePort                   # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:    
    app: willow-api                # Selects any Pod with labels `app=willow-api`
  ports:
      - name: backend-port
        port: 5000
        targetPort: 5000
        protocol: TCP
        
      