apiVersion: v1
kind: Service
metadata:      
  name: client-cluster-ip-service
spec:
  type: NodePort
  selector:    
    component: client  
  ports:    
      - port: 80      
        targetPort: 80
        protocol: TCP
        nodePort: 31000
  