apiVersion: v1
kind: Service
metadata:      
  name: willow
  labels: 
    run: willow
spec:
  type: NodePort
  selector:    
    app: willow  
  ports:    
      - port: 80
        protocol: TCP
        name: frontend-port


